// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MapIndexLessNamespace {
  export interface IMapIndexLess {
    changeButton: string;
  }
}

declare const MapIndexLessModule: MapIndexLessNamespace.IMapIndexLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MapIndexLessNamespace.IMapIndexLess;
};

export = MapIndexLessModule;
